# Interface name.
string interface_name

# The type of message associated with the interface.
string message_type

# The name of the associated service for getting a message.
string get_service_name

# The service message of the service for getting a message.
string get_service_type

# The name of the associated service for setting a message.
string set_service_name

# The service message of the service for setting a message.
string set_service_type

string interface_type

# Timestamp of the last added message through this interface.
time timestamp
